### PR TITLE
Add Orks Kill Team

### PR DESCRIPTION
**Pull request by ebruning**
Added the stats for Orks

### CODE REVIEW

**Comment by AppSynergy** [comment]
Thanks again for this addition!

Spanner boy, lol. Is that really what they are called?

**Comment by AppSynergy** [comment]
I'm assuming:

```
[weapons.basic.shoota]
name = "Boltgun"
cost = 35

[weapons.special.flamer]
name = "Shoota"
cost = 25
```

is supposed to be: 

```
[weapons.basic.shoota]
name = "Shoota"
cost = 25
```

**Comment by AppSynergy** [comment]
Can a nob use special weapons? It looks like they should be able to.

Is there not more than one type of kombi-weapon?

**Comment by ebruning** [comment]
No Thanks for making this! 

You are correct about the shoota.

I doubled checked and only the Spanner Bou can take special weapons.

There are only Kombi-Shoota and Kombi-Weapons

**Comment by AppSynergy** [comment]
This can't be right then:

```
[weapons.special.kombi-shoota]
name = "Kombi-shoota"
cost = 40
only_fighter = ["boss_nob"]

[weapons.special.kombi-weapon]
name = "Kombi-weapon"
cost = 50
only_fighter = ["boss_nob"]
```

If they are special, only the spanner boy can take them, but only the boss nob can take them, so no-one can take them!

**Comment by ebruning** [comment]
ok, I see what I did. Kombi-shoota and kombi-weapon aren't special they are basic. Apparently, I need to finish my coffee before coding. I'll fix this now

**Pull request merged**
